add new PUBNOTICES level
ailin-nemui/irssi pull request #81
Opened 2022-04-19 08:53 UTC by ailin-nemui

separating private notices and channel notices

2022-04-20 22:14 UTC, horgh requested changes
Cool!

2022-04-20 22:14 UTC, horgh commented on src/fe-common/irc/fe-irc-messages.c
> +	                      TRUE))
Do we need to free cchannel in this case?

2022-04-20 22:14 UTC, horgh commented on themes/default.theme
>    pubnotice_channel = "%K:%m$*";
Do we need this now? I see we don't use it above any more. (I'm not sure!) Likewise with `pvtnotice_host`.

2022-04-20 22:14 UTC, horgh commented on src/fe-common/irc/module-formats.c
> +	{ "notice_private", "{notice $0}$2", 3, { 0, 0, 0 } },
If we aren't using $1 here, would we want to stop passing it to the format? Or would that break some existing themes or something?

Also does changing from e.g. pubnotice_channel to pubnotice mean any issues for existing themes? (I don't know)

2022-04-21 11:00 UTC, ailin-nemui commented on docs/help/in/levels.in
> +        NOTICES         Private Notices sent from a nickname.
that makes sense

2022-04-21 11:02 UTC, ailin-nemui commented on src/fe-common/irc/fe-irc-messages.c
> +	cchannel = is_public ? NULL : notice_channel_context((SERVER_REC *) server, msg);
the meaning of `cchannel` was intended to be `contextual channel`, as retrieved by the notice_channel_context method. These are actually private notices that start with [#channel] by convention (IRCx WHISPER emulation)

2022-04-21 11:03 UTC, ailin-nemui commented on src/fe-common/irc/fe-irc-messages.c
> +	                      TRUE))
very good catch

2022-04-21 11:04 UTC, ailin-nemui commented on themes/default.theme
>    pubnotice_channel = "%K:%m$*";
I think it's best to leave in for backward compatibility and to not break other themes that might depend on it.

2022-04-21 11:05 UTC, ailin-nemui commented on src/fe-common/irc/module-formats.c
> +	{ "notice_private", "{notice $0}$2", 3, { 0, 0, 0 } },
yes, it will break themes (in a sense that their pubnotice rendering might look "off"/ not themed), but  I don't think that can be helped. should put a note about it in the NEWS

2022-04-21 11:07 UTC, ailin-nemui commented on src/fe-common/irc/module-formats.c
> +	{ "notice_private", "{notice $0}$2", 3, { 0, 0, 0 } },
the reason we should try to not touch the arguments is that people can restore the old format if they prefer it, and if the numbers change it would break themes that have a format for notice_public

2022-04-21 17:22 UTC, horgh requested changes
Looks great!

2022-04-21 17:22 UTC, horgh commented on src/fe-common/irc/fe-irc-messages.c
> +	if (is_public) {
Would we want to follow this branch if `context_channel` is not null too? Just noticing the else branch has some "private" stuff, though I see it also uses `context_channel`. I'm not sure!

2022-04-21 18:27 UTC, ailin-nemui commented on src/fe-common/irc/fe-irc-messages.c
> +	if (is_public) {
thanks for taking a closer look. basically I didn't change the old code at all (even though it doesn't seem like!)
so the intention is that it should still be the same as the old code, except for the added pubnotices level

2022-04-21 18:54 UTC, horgh approved these changes

2022-04-21 19:09 UTC, merged